services:
  - type: web
    name: maksocial
    runtime: php
    buildCommand: "./build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=8080"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database

  - type: postgres
    name: maksocial-db
    plan: free
    diskSizeGB: 1